print("Carl Salido Madrigal")
print("Brgy. Dili, Gasan, Marinduque")
print("September 22, 2003")
print("College of Information and Computing Science")
print("BSIT")
print("2A")
print("Watching")
print("Playing ML")
print("Reading Comics")
print("Playing Chess")
print("Drawing")